### ISSUE TITLE
Maak van level een Enum

### ISSUE THREAD

**Issue by braekstuv** [Tjoeker/ProjectCalculator#1]
Contextuele waarden (hier als in: plus of min, maal of gedeeld door,...) kunnen beter in een enum gezet worden. Het is op andere plekken onduidelijk om te lezen wat welk level inhoudt, tenzij men de comment leest op deze lijn. Als je een enumwaarde gebruikt, zal dit dan bvb lezen als level == Level.PlusOfMaal, dan hoeft men niet meer op te zoeken wat de effectieve waarde is van level.

https://github.com/Tjoeker/ProjectCalculator/blob/531f6cd04a8fe582a5b8e19bb4907c98814931ab/Calculator/Class1.cs#L81

**Comment by Tjoeker** [comment]
Fixed
