### ISSUE TITLE
Naming niet duidelijk

### ISSUE THREAD

**Issue by braekstuv** [Tjoeker/ProjectCalculator#4]
"Main" is een methodenaam die normaal gebruikt wordt om een applicatie op te starten binnen Program.cs. Hier werken we echter niet met een applicatie maar een class. Gebruik een duidelijke term (zoals "Calculate" of iets dergelijks) om duidelijk te zijn over wat de methode doet.

https://github.com/Tjoeker/ProjectCalculator/blob/531f6cd04a8fe582a5b8e19bb4907c98814931ab/Calculator/Class1.cs#L217

**Comment by Tjoeker** [comment]
Fixed
