### ISSUE TITLE
ParseFunction & LosOp

### ISSUE THREAD

**Issue by braekstuv** [Tjoeker/ProjectCalculator#5]
Deze twee methodes bevatten veel geneste stukken code, waardoor de complexiteit en leesbaarheid van die methode verhoogt. Probeer deze twee functies om te vormen naar meerdere submethodes. 

https://github.com/Tjoeker/ProjectCalculator/blob/531f6cd04a8fe582a5b8e19bb4907c98814931ab/Calculator/Class1.cs#L11

**Comment by Tjoeker** [comment]
Fixed
